//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentSChedule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int AccountId { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<int> RuleId { get; set; }
        public Nullable<int> TeacherId { get; set; }
    
        public virtual Rule Rule { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
