//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentSChedule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.ScheduleLessons = new HashSet<ScheduleLesson>();
            this.Students = new HashSet<Student>();
        }
    
        public int GroupId { get; set; }
        public string GroupName { get; set; }
    
        public virtual ICollection<ScheduleLesson> ScheduleLessons { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
