//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentSChedule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rule
    {
        public Rule()
        {
            this.Accounts = new HashSet<Account>();
        }
    
        public int RuleId { get; set; }
        public string RuleName { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
    }
}
