//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentSChedule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleLesson
    {
        public int ScheduleId { get; set; }
        public Nullable<int> LessonId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> TeacherId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> AudienceId { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<bool> TopFlag { get; set; }
    
        public virtual Audience Audience { get; set; }
        public virtual Group Group { get; set; }
        public virtual Lesson Lesson { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
