//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentSChedule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Evaluations = new HashSet<Evaluation>();
        }
    
        public int StudentId { get; set; }
        public string StudentFirstName { get; set; }
        public string StudentName { get; set; }
        public string StudentLastName { get; set; }
        public Nullable<int> GroupId { get; set; }
    
        public virtual ICollection<Evaluation> Evaluations { get; set; }
        public virtual Group Group { get; set; }
    }
}
