//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentSChedule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.Accounts = new HashSet<Account>();
            this.Evaluations = new HashSet<Evaluation>();
            this.ScheduleLessons = new HashSet<ScheduleLesson>();
        }
    
        public int TeacherId { get; set; }
        public string TeacherFirstName { get; set; }
        public string TeacherName { get; set; }
        public string TeacherLastName { get; set; }
        public string TeacherPassword { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<Evaluation> Evaluations { get; set; }
        public virtual ICollection<ScheduleLesson> ScheduleLessons { get; set; }
    }
}
